componentName: payment
image:
  component: payment
health:
  path: /health
  port: "8080"
configMap:
  enabled: true
  data:
    CART_HOST: cart
    CART_PORT: "80"
    USER_HOST: "user"
    USER_PORT: "80"
    AMQP_HOST: rabbitmq
    AMQP_USER: roboshop
    AMQP_PASS: roboshop123
resources:
   limits:
     cpu: 1000m
     memory: 1024Mi
   requests:
     cpu: 1000m
     memory: 1024Mi
